# Generated by Django 5.1 on 2024-08-23 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[(1, 'CAFE'), (2, 'USER')], default=1, max_length=4),
            preserve_default=False,
        ),
    ]
