# Generated by Django 5.1 on 2024-08-23 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('CAFE', 1), ('USER', 2)], max_length=4),
        ),
    ]
