# Generated by Django 5.1 on 2024-08-23 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='cafe',
            new_name='category',
        ),
    ]
