# Generated by Django 5.1 on 2024-08-23 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_rename_cafe_productmodel_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='quantity',
        ),
    ]
